import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Headline from '../components/Headline'
import Posts from '../components/Posts'
import AsideArticles from '../components/AsideArticles'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Headline />
      <section className={styles.sections}>
        <Posts />
        <AsideArticles />
      </section>
      
    </div>
  )
}
